### ISSUE TITLE
Updated Aurelia

### ISSUE THREAD

**Issue by johntom** [jdanyow/aurelia-breeze-northwind#10]
Hi,
I tried to update this repo with latest from aurelia
1) jspm install aurelia-animator-css aurelia-binding aurelia-bootstrapper aurelia-dependency-injection aurelia-framework aurelia-http-client aurelia-router aurelia-event-aggregator aurelia-history-browser aurelia-loader-default aurelia-loader aurelia-metadata aurelia-route-recognizer aurelia-templating-binding aurelia-templating-resources aurelia-templating-router aurelia-templating aurelia-logging aurelia-task-queue aurelia-history aurelia-path
2) change references from path@0.8.0 to path@0.9.0",
task-queue@0.6.0", to 7.0
logging@0.6 to 7.0
3) change /resources/index
// export function configure(aurelia) {
//   aurelia.globalizeResources('./date-format', './number-format', './materialize', './pager');
// }
export function configure(config) {
  config.globalResources('./date-format', './number-format', './materialize', './pager');
}

error
Unhandled promise rejection TypeError: aurelia.withInstance is not a function
    at y.configure (http://localhost:9000/jspm_packages/github/jdanyow/aurelia-breeze@0.7.0/index.js:17:13)
    at http://localhost:9000/jspm_packages/github/aurelia/framework@0.16.0/aurelia-framework.js:34:34
    at run (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/modules/es6.promise.js:91:43)
    at http://localhost:9000/jspm_packages/npm/core-js@0.9.18/modules/es6.promise.js:105:11
    at module.exports (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/modules/$.invoke.js:6:25)
    at queue.(anonymous function) (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/modules/$.task.js:40:9)
    at Number.run (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/modules/$.task.js:27:7)
    at listner (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/modules/$.task.js:31:9)

4) change jdanyow/aurelia-breeze@0.7.0/index.js 
from aurelia.withInstance to aurelia.singleton
gulp watch

failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:9000/dist/resources/index/number-format.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:9000/dist/resources/index/materialize.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:9000/dist/resources/index/pager.js Failed to load resource: the server responded with a status of 404 (Not Found)
3:9000/jspm_packages/npm/core-js@0.9.18/modules/es6.promise.js:139 Unhandled promise rejection Error loading "resources/index/number-format" at http://localhost:9000/dist/resources/index/number-format.js
Not Found: http://localhost:9000/dist/resources/index/number-format.js

**Comment by johntom** [comment]
i found the doing the following fixed my issues.
npm install jspm --save-dev
npm instal gulp
